"""Create a compact, hashable reproducibility manifest for the submission."""
from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import platform
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

FILES = [
    "paper/theory.md", "paper/draft.md", "paper/experiments_draft.md",
    "paper/evidence_matrix.md", "paper/submission_checklist.md", "paper/STATUS.md",
    "paper/claim_ledger.md",
    "paper/tables.md", "paper/figure_manifest.md", "paper/submission.tex", "paper/submission.pdf",
    "results_submission/README.md", "results_submission/report/REPORT.md",
    "results_submission/report/evidence_audit.json",
    "results_submission/report/main_table.csv", "results_submission/report/main_table_ci.csv",
    "results_submission/report/interactive_main_table/summary.csv",
    "results_submission/report/interactive_main_table/contrasts.csv",
    "results_submission/report/interactive_main_table/metadata.json",
    "results_submission/report/scienceworld_interactive_aggregate/summary.csv",
    "results_submission/report/scienceworld_interactive_aggregate/paired_bootstrap.csv",
    "results_submission/report/scienceworld_interactive_aggregate/metadata.json",
    "results_submission/report/scienceworld_recharged_llm_extension/summary.csv",
    "results_submission/report/scienceworld_recharged_llm_extension/paired_bootstrap.csv",
    "results_submission/report/scienceworld_recharged_animal_llm_extension/summary.csv",
    "results_submission/report/scienceworld_recharged_animal_llm_extension/paired_bootstrap.csv",
    "results_submission/provenance_semantic_hard_final/summary.json",
    "results_submission/provenance_semantic_hard_final/margin_analysis.csv",
    "results_submission/provenance_semantic_hard_final/identifiability_null.csv",
    "results_submission/benchmark/stats.json",
    "results_submission/benchmark/lineage_example.svg",
    "results_submission/report/api_status.json",
    "results_submission/scienceworld_frozen_readout_clean_20260929/manifest.json",
    "results_submission/scienceworld_frozen_readout_clean_20260929/states.json",
    "results_submission/scienceworld_frozen_readout_clean_20260929/summary.csv",
    "results_submission/scienceworld_frozen_readout_clean_20260929/paired.csv",
    "results_submission/scienceworld_frozen_readout_clean_20260929/bootstrap.csv",
    "results_submission/scienceworld_frozen_readout_clean_20260929/audit.json",
    "results_submission/scienceworld_frozen_readout_first4_20260929/manifest.json",
    "results_submission/scienceworld_frozen_readout_first4_20260929/states.json",
    "results_submission/scienceworld_frozen_readout_first4_20260929/summary.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/paired.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/bootstrap.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/audit.json",
    "results_submission/scienceworld_frozen_readout_first4_20260929/curve.png",
    "results_submission/scienceworld_frozen_readout_first4_20260929/ANALYSIS.md",
    "results_submission/scienceworld_frozen_readout_first4_20260929/episode_bootstrap.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/episode_units.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/paired_events.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/joint_events.csv",
    "results_submission/scienceworld_frozen_readout_first4_20260929/verified_analysis.json",
    "results_submission/scienceworld_frozen_readout_first4_20260929/episode_curves.png",
    "results_submission/scienceworld_frozen_readout_first4_20260929/qualitative_events.md",
    "results_submission/report/scienceworld_input_integrity/summary.json",
    "results_submission/report/scienceworld_input_integrity/requests.csv",
    "results_submission/deepseek_mvp_20260929/metadata.json",
    "results_submission/deepseek_mvp_20260929/rows.csv",
    "results_submission/deepseek_mvp_20260929/summary.csv",
    "results_submission/deepseek_mvp_20260929/paired.csv",
    "results_submission/deepseek_mvp_20260929/bootstrap.csv",
    "results_submission/deepseek_mvp_20260929/same_body_control.csv",
    "results_submission/deepseek_mvp_20260929/curve.png",
    "results_submission/report/scienceworld_local_qwen_mvp/metadata.json",
    "results_submission/report/scienceworld_local_qwen_mvp/rows.csv",
    "results_submission/report/scienceworld_local_qwen_mvp/summary.csv",
    "results_submission/report/scienceworld_local_qwen_mvp/paired.csv",
    "results_submission/report/local_qwen_episode_pilot/metadata.json",
    "results_submission/report/local_qwen_episode_pilot/rows.csv",
    "results_submission/report/local_qwen_episode_pilot/summary.csv",
    "results_submission/report/local_qwen_episode_pilot/paired.csv",
    "results_submission/report/local_qwen_episode_pilot/bootstrap.csv",
    "results_submission/report/local_qwen_expanded_pilot/metadata.json",
    "results_submission/report/local_qwen_expanded_pilot/rows.csv",
    "results_submission/report/local_qwen_expanded_pilot/summary.csv",
    "results_submission/report/local_qwen_expanded_pilot/paired.csv",
    "results_submission/report/local_qwen_expanded_pilot/bootstrap.csv",
    "results_submission/report/local_qwen_expanded_pilot/raw_errors.csv",
    "results_submission/report/local_qwen_expanded_pilot/curve.png",
    "results_submission/report/local_qwen_value_replay/metadata.json",
    "results_submission/report/local_qwen_value_replay/rows.csv",
    "results_submission/report/local_qwen_value_replay/summary.csv",
    "results_submission/report/local_qwen_value_replay/paired.csv",
    "results_submission/report/local_qwen_value_replay/bootstrap.csv",
    "results_submission/report/local_qwen_value_replay/cache_audit.json",
    "results_submission/report/local_qwen_animal_value_replay/metadata.json",
    "results_submission/report/local_qwen_animal_value_replay/rows.csv",
    "results_submission/report/local_qwen_animal_value_replay/summary.csv",
    "results_submission/report/local_qwen_animal_value_replay/paired.csv",
    "results_submission/report/local_qwen_animal_value_replay/bootstrap.csv",
    "results_submission/report/local_qwen_animal_expanded_pilot/metadata.json",
    "results_submission/report/local_qwen_animal_expanded_pilot/rows.csv",
    "results_submission/report/local_qwen_animal_expanded_pilot/summary.csv",
    "results_submission/report/local_qwen_animal_expanded_pilot/paired.csv",
    "results_submission/report/local_qwen_animal_expanded_pilot/bootstrap.csv",
    "results_submission/report/local_qwen_animal_expanded_pilot/raw_errors.csv",
    "results_submission/report/local_qwen_interactive_main_table/metadata.json",
    "results_submission/report/local_qwen_interactive_main_table/rows.csv",
    "results_submission/report/local_qwen_interactive_main_table/summary.csv",
    "results_submission/report/local_qwen_interactive_main_table/paired.csv",
    "results_submission/report/local_qwen_interactive_main_table/contrasts.csv",
    "results_submission/report/local_qwen_interactive_main_table/curve.png",
    "results_submission/report/cross_model_interactive_table/metadata.json",
    "results_submission/report/cross_model_interactive_table/strata.csv",
    "results_submission/report/cross_model_interactive_table/ranges.csv",
    "results_submission/report/alfworld_interactive/metadata.json",
    "results_submission/report/alfworld_interactive/rows.csv",
    "results_submission/report/alfworld_interactive/summary.csv",
    "results_submission/report/alfworld_interactive/paired.csv",
    "results_submission/report/alfworld_interactive/paired_algorithmic.csv",
    "results_submission/report/alfworld_interactive/paired_objectives.csv",
    "results_submission/report/alfworld_interactive/action_consistency.csv",
    "results_submission/report/alfworld_interactive/bootstrap.csv",
    "results_submission/report/alfworld_interactive/action_bootstrap.csv",
    "results_submission/report/alfworld_interactive/curve.png",
    "results_submission/report/local_qwen_expansion_162_164/metadata.json",
    "results_submission/report/local_qwen_expansion_162_164/rows.csv",
    "results_submission/report/local_qwen_expansion_162_164/summary.csv",
    "results_submission/report/local_qwen_expansion_162_164/paired.csv",
    "results_submission/report/local_qwen_expansion_162_164/bootstrap.csv",
    "results_submission/report/local_qwen_expansion_162_164/action_consistency.csv",
    "results_submission/report/local_qwen_expansion_162_164/action_bootstrap.csv",
    "results_submission/report/local_qwen_expansion_162_164/curve.png",
    "results_submission/report/local_qwen_expansion_165_167/metadata.json",
    "results_submission/report/local_qwen_expansion_165_167/rows.csv",
    "results_submission/report/local_qwen_expansion_165_167/summary.csv",
    "results_submission/report/local_qwen_expansion_165_167/paired.csv",
    "results_submission/report/local_qwen_expansion_165_167/bootstrap.csv",
    "results_submission/report/local_qwen_expansion_165_167/raw_errors.csv",
    "results_submission/report/local_qwen_expansion_165_167/action_consistency.csv",
    "results_submission/report/local_qwen_expansion_165_167/action_bootstrap.csv",
    "results_submission/report/local_qwen_expansion_165_167/curve.png",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/metadata.json",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/rows.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/summary.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/paired.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/bootstrap.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/raw_errors.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/action_consistency.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/action_bootstrap.csv",
    "results_submission/report/local_qwen_fair_flatvalue_168_169/curve.png",
    "results_submission/report/local_qwen_expansion_170_171/metadata.json",
    "results_submission/report/local_qwen_expansion_170_171/rows.csv",
    "results_submission/report/local_qwen_expansion_170_171/summary.csv",
    "results_submission/report/local_qwen_expansion_170_171/paired.csv",
    "results_submission/report/local_qwen_expansion_170_171/bootstrap.csv",
    "results_submission/report/local_qwen_expansion_170_171/raw_errors.csv",
    "results_submission/report/local_qwen_expansion_170_171/action_consistency.csv",
    "results_submission/report/local_qwen_expansion_170_171/action_bootstrap.csv",
    "results_submission/report/local_qwen_expansion_170_171/curve.png",
    "results_submission/report/local_qwen_expansion_170_171_retry/metadata.json",
    "results_submission/report/local_qwen_expansion_170_171_retry/rows.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/summary.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/paired.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/bootstrap.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/raw_errors.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/action_consistency.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/action_bootstrap.csv",
    "results_submission/report/local_qwen_expansion_170_171_retry/curve.png",
    "results_submission/report/local_qwen_expansion_172_173/metadata.json",
    "results_submission/report/local_qwen_expansion_172_173/rows.csv",
    "results_submission/report/local_qwen_expansion_172_173/summary.csv",
    "results_submission/report/local_qwen_expansion_172_173/paired.csv",
    "results_submission/report/local_qwen_expansion_172_173/bootstrap.csv",
    "results_submission/report/local_qwen_expansion_172_173/raw_errors.csv",
    "results_submission/report/local_qwen_expansion_172_173/action_consistency.csv",
    "results_submission/report/local_qwen_expansion_172_173/action_bootstrap.csv",
    "results_submission/report/local_qwen_expansion_172_173/curve.png",
    "results_submission/report/local_qwen_effect_heterogeneity/metadata.json",
    "results_submission/report/local_qwen_effect_heterogeneity/heterogeneity.csv",
    "results_submission/report/local_qwen_effect_heterogeneity/forest.png",
    "results_submission/report/local_qwen_heldout174_176/metadata.json",
    "results_submission/report/local_qwen_heldout174_176/rows.csv",
    "results_submission/report/local_qwen_heldout174_176/summary.csv",
    "results_submission/report/local_qwen_heldout174_176/paired.csv",
    "results_submission/report/local_qwen_heldout174_176/bootstrap.csv",
    "results_submission/report/local_qwen_heldout174_176/action_consistency.csv",
    "results_submission/report/local_qwen_heldout174_176/action_bootstrap.csv",
    "results_submission/report/local_qwen_heldout174_176/curve.png",
    "results_submission/report/local_qwen_heldout177_179/metadata.json",
    "results_submission/report/local_qwen_heldout177_179/rows.csv",
    "results_submission/report/local_qwen_heldout177_179/summary.csv",
    "results_submission/report/local_qwen_heldout177_179/paired.csv",
    "results_submission/report/local_qwen_heldout177_179/bootstrap.csv",
    "results_submission/report/local_qwen_heldout177_179/action_consistency.csv",
    "results_submission/report/local_qwen_heldout177_179/action_bootstrap.csv",
    "results_submission/report/local_qwen_heldout177_179/curve.png",
    "results_submission/qwen_semantic_bank_probe/protocol.json",
    "results_submission/qwen_semantic_bank_probe/states.json",
    "results_submission/qwen_semantic_bank_probe/results.json",
    "results_submission/qwen_semantic_bank_probe/rows.csv",
    "results_submission/qwen_semantic_bank_probe/summary.csv",
    "results_submission/qwen_semantic_bank_probe/ANALYSIS.md",
    "results_submission/report/qwen_bank_diagnostic/metadata.json",
    "results_submission/report/qwen_bank_diagnostic/steps.csv",
    "results_submission/report/qwen_bank_diagnostic/episodes.csv",
    "results_submission/report/qwen_bank_diagnostic/summary.csv",
    "results_submission/report/qwen_bank_diagnostic/ANALYSIS.md",
    "results_submission/report/local_qwen_interactive_expanded_table/metadata.json",
    "results_submission/report/local_qwen_interactive_expanded_table/rows.csv",
    "results_submission/report/local_qwen_interactive_expanded_table/summary.csv",
    "results_submission/report/local_qwen_interactive_expanded_table/paired.csv",
    "results_submission/report/local_qwen_interactive_expanded_table/contrasts.csv",
    "results_submission/report/local_qwen_interactive_expanded_table/curve.png",
    "results_submission/report/local_qwen_interactive_expanded_table_v3/metadata.json",
    "results_submission/report/local_qwen_interactive_expanded_table_v3/rows.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v3/summary.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v3/paired.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v3/contrasts.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v3/curve.png",
    "results_submission/report/local_qwen_interactive_expanded_table_v4/metadata.json",
    "results_submission/report/local_qwen_interactive_expanded_table_v4/rows.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v4/summary.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v4/paired.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v4/contrasts.csv",
    "results_submission/report/local_qwen_interactive_expanded_table_v4/curve.png",
    "results_submission/alfworld_interactive_v7_deepseek/metadata.json",
    "results_submission/alfworld_interactive_v7_deepseek/episode_manifest.json",
    "results_submission/alfworld_interactive_v8_qwen/metadata.json",
    "results_submission/alfworld_interactive_v8_qwen/episode_manifest.json",
    "results_submission/alfworld_interactive_v9_deepseek_success/metadata.json",
    "results_submission/alfworld_interactive_v9_deepseek_success/episode_manifest.json",
    "results_submission/alfworld_interactive_v10_deepseek/metadata.json",
    "results_submission/alfworld_interactive_v10_deepseek/episode_manifest.json",
    "results_submission/alfworld_interactive_v12_deepseek_flatvalue/metadata.json",
    "results_submission/alfworld_interactive_v12_deepseek_flatvalue/episode_manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_162_164_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_162_164_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_162_164_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_162_164_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_165_167_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_165_167_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_165_167_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_165_167_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_retry_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_retry_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_retry_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_170_171_retry_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_172_173_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_172_173_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_expansion_172_173_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_expansion_172_173_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_value_grid_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_value_grid_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_value_grid_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_value_grid_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_value_grid_v9_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_value_grid_v9_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_grid150_155_v9_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_grid150_155_v9_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_value161_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_value161_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_value161_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_value161_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_value161_v9_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_value161_v9_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_grid150_155_v9_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_grid150_155_v9_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_heldout174_176_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_heldout174_176_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_heldout174_176_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_heldout174_176_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_heldout177_179_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_heldout177_179_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_heldout177_179_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_heldout177_179_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_provenance_value_current_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_provenance_value_current_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_provenance_value_current_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_provenance_value_current_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_provenance_value_158_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_provenance_value_158_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_provenance_value_158_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_provenance_value_158_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_provenance_value_161_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_provenance_value_161_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_provenance_value_161_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_provenance_value_161_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_animal153_v9_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_animal153_v9_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_animal153_v9_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_animal153_v9_m4/summaries.json",
    "results_submission/scienceworld_local_qwen_animal150_155_v9_m1/manifest.json",
    "results_submission/scienceworld_local_qwen_animal150_155_v9_m1/summaries.json",
    "results_submission/scienceworld_local_qwen_animal150_155_v9_m4/manifest.json",
    "results_submission/scienceworld_local_qwen_animal150_155_v9_m4/summaries.json",
    "results_submission/report/local_qwen_gpu_probe.json",
]

SCRIPTS = [
    "submission/benchmark.py", "submission/benchmark_eval.py", "submission/ablation.py",
    "submission/provenance_recovery.py", "submission/provenance_semantic_hard.py",
    "submission/scienceworld_runner.py", "submission/recharged_scienceworld.py",
    "submission/recharged_extension_summary.py", "submission/recharged_llm_extension_summary.py",
    "submission/recharged_counterfactual.py", "submission/scienceworld_interactive_aggregate.py",
    "submission/interactive_main_table.py", "submission/report.py",
    "submission/evidence_audit.py", "submission/evidence_matrix.py",
    "submission/requirement_checklist.py", "submission/reproducibility_manifest.py", "submission/make_submission_pdf.py",
    "submission/scienceworld_frozen_readout.py", "submission/scienceworld_frozen_readout_expand.py", "submission/scienceworld_input_audit.py",
    "submission/deepseek_mvp.py", "submission/local_qwen_mvp_summary.py", "submission/local_qwen_gpu_probe.py",
    "submission/scienceworld_fixedbank_analysis.py",
    "submission/local_qwen_episode_pilot_summary.py",
    "submission/local_qwen_expanded_summary.py",
    "submission/local_qwen_value_replay_summary.py",
    "submission/local_qwen_animal_value_summary.py",
    "submission/local_qwen_animal_expanded_summary.py",
    "submission/local_qwen_interactive_main_table.py",
    "submission/local_qwen_expansion_summary.py", "submission/local_qwen_expanded_main_table.py",
    "submission/flatvalue_expansion_summary.py",
    "submission/paper_tables.py",
    "submission/qwen_effect_heterogeneity.py",
    "submission/qwen_bank_diagnostic.py", "submission/qwen_semantic_bank_probe.py",
    "submission/claim_ledger.py",
    "submission/cross_model_interactive_table.py",
    "submission/alfworld_interactive_runner.py", "submission/cuda_json_worker.py",
    "submission/alfworld_interactive_summary.py",
    "submission/llm.py",
]

COMMANDS = [
    "python -m submission.benchmark --output results_submission/benchmark --instances-per-family 1000 --rollouts-per-action 4",
    "python -m submission.benchmark_eval --benchmark results_submission/scaling_benchmark --output results_submission/scaling --budgets 1,2,4,8,16,32,64",
    "python -m submission.provenance_semantic_hard --benchmark results_submission/scaling_benchmark --output results_submission/provenance_semantic_hard_final",
    "python -m submission.scienceworld_interactive_aggregate",
    "python -m submission.interactive_main_table",
    "python -m submission.report",
    "python -m submission.evidence_audit",
    "python -m submission.evidence_matrix",
    "python -m submission.requirement_checklist",
    "python -m submission.scienceworld_input_audit",
    "python -m submission.scienceworld_frozen_readout prepare",
    "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY .venv-research/bin/python -m submission.scienceworld_frozen_readout run --workers 2",
    ".venv-research/bin/python -m submission.scienceworld_frozen_readout replay",
    ".venv-research/bin/python -m submission.scienceworld_frozen_readout summarize",
    "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY python -m submission.deepseek_mvp --output results_submission/deepseek_mvp_20260929",
    "python -m submission.scienceworld_frozen_readout_expand prepare --output results_submission/scienceworld_frozen_readout_first4_20260929 --all-steps --max-step 4",
    "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY python -m submission.scienceworld_frozen_readout_expand run --output results_submission/scienceworld_frozen_readout_first4_20260929 --workers 6",
    "PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_frozen_readout_expand replay --output results_submission/scienceworld_frozen_readout_first4_20260929",
    "python -m submission.scienceworld_frozen_readout_expand summarize --output results_submission/scienceworld_frozen_readout_first4_20260929",
    "python -m submission.scienceworld_fixedbank_analysis --directory results_submission/scienceworld_frozen_readout_first4_20260929",
    "python -m submission.local_qwen_mvp_summary",
    "CUDA_VISIBLE_DEVICES=0 PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.local_qwen_gpu_probe",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant --variation-ids find-plant:152,find-plant:158,find-plant:161 --methods flat provenance_success --duplication 1 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_value_grid_v9_m1",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant --variation-ids find-plant:152,find-plant:158 --methods flat provenance_success --duplication 4 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_value_grid_m4",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant --variation-ids find-plant:161 --methods flat provenance_success --duplication 4 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_value161_v9_m4",
    "python -m submission.local_qwen_episode_pilot_summary",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant --variation-ids find-plant:150,find-plant:151,find-plant:152,find-plant:153,find-plant:154,find-plant:155 --methods flat provenance_success --duplication 1 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_grid150_155_v9_m1",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant --variation-ids find-plant:150,find-plant:151,find-plant:152,find-plant:153,find-plant:154,find-plant:155 --methods flat provenance_success --duplication 4 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_grid150_155_v9_m4",
    "python -m submission.local_qwen_expanded_summary",
    "python -m submission.local_qwen_value_replay_summary",
    "python -m submission.local_qwen_interactive_main_table",
    "python -m submission.claim_ledger",
    "python -m submission.cross_model_interactive_table",
    "python -m submission.alfworld_interactive_summary",
    ".venv-research/bin/python -m submission.alfworld_interactive_runner --help",
    "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY ALFWORLD_DATA=external/alfworld_data .venv-research/bin/python -m submission.alfworld_interactive_runner --backend deepseek --output results_submission/alfworld_interactive_v7_deepseek --task-types 1,2,3,4,5,6 --games-per-type 1 --steps 12 --duplications 1,4 --methods no_imagination,flat,provenance_value",
    "LOCAL_QWEN_DEVICE=cuda ALFWORLD_DATA=external/alfworld_data .venv-research/bin/python -m submission.alfworld_interactive_runner --backend cuda_worker --cuda-python /home/xhj/miniconda3/bin/python --output results_submission/alfworld_interactive_v8_qwen --task-types 1,2,3,4,5,6 --games-per-type 1 --steps 12 --duplications 1,4 --methods no_imagination,flat,provenance_value",
    "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY ALFWORLD_DATA=external/alfworld_data .venv-research/bin/python -m submission.alfworld_interactive_runner --backend deepseek --output results_submission/alfworld_interactive_v9_deepseek_success --task-types 1,2,3,4,5,6 --games-per-type 1 --steps 12 --duplications 1,4 --methods provenance_success",
    "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY ALFWORLD_DATA=external/alfworld_data .venv-research/bin/python -m submission.alfworld_interactive_runner --backend deepseek --output results_submission/alfworld_interactive_v10_deepseek --task-types 1,2,3,4,5,6 --games-per-type 1 --game-offset 1 --steps 12 --duplications 1,4 --methods no_imagination,flat,provenance_value",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant find-animal --variation-ids find-plant:162,find-plant:163,find-plant:164,find-animal:162,find-animal:163,find-animal:164 --methods flat provenance_value --duplication 1 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_expansion_162_164_m1",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --tasks find-plant find-animal --variation-ids find-plant:162,find-plant:163,find-plant:164,find-animal:162,find-animal:163,find-animal:164 --methods flat provenance_value --duplication 4 --steps 8 --workers 1 --backend local_qwen --output results_submission/scienceworld_local_qwen_expansion_162_164_m4",
    "python -m submission.local_qwen_expansion_summary --m1 results_submission/scienceworld_local_qwen_expansion_162_164_m1 --m4 results_submission/scienceworld_local_qwen_expansion_162_164_m4 --output results_submission/report/local_qwen_expansion_162_164",
    "/home/xhj/miniconda3/bin/python -c \"import sys; sys.path.append('/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages'); from submission.scienceworld_runner import main; main()\" --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:165,find-plant:166,find-plant:167,find-animal:165,find-animal:166,find-animal:167 --methods flat provenance_value --duplication 1 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_expansion_165_167_m1",
    "cp -a results_submission/scienceworld_local_qwen_expansion_165_167_m1/requests results_submission/scienceworld_local_qwen_expansion_165_167_m4",
    "/home/xhj/miniconda3/bin/python -c \"import sys; sys.path.append('/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages'); from submission.scienceworld_runner import main; main()\" --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:165,find-plant:166,find-plant:167,find-animal:165,find-animal:166,find-animal:167 --methods flat provenance_value --duplication 4 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_expansion_165_167_m4",
    "python -m submission.local_qwen_expansion_summary --m1 results_submission/scienceworld_local_qwen_expansion_165_167_m1 --m4 results_submission/scienceworld_local_qwen_expansion_165_167_m4 --output results_submission/report/local_qwen_expansion_165_167",
    "/home/xhj/miniconda3/bin/python -c \"import sys; sys.path.append('/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages'); from submission.scienceworld_runner import main; main()\" --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:168,find-plant:169,find-animal:168,find-animal:169 --methods flat_value provenance_value --duplication 1 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_flatvalue_168_169_m1",
    "cp -a results_submission/scienceworld_local_qwen_flatvalue_168_169_m1/requests results_submission/scienceworld_local_qwen_flatvalue_168_169_m4",
    "/home/xhj/miniconda3/bin/python -c \"import sys; sys.path.append('/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages'); from submission.scienceworld_runner import main; main()\" --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:168,find-plant:169,find-animal:168,find-animal:169 --methods flat_value provenance_value --duplication 4 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_flatvalue_168_169_m4",
    "python -m submission.flatvalue_expansion_summary --m1 results_submission/scienceworld_local_qwen_flatvalue_168_169_m1 --m4 results_submission/scienceworld_local_qwen_flatvalue_168_169_m4 --output results_submission/report/local_qwen_fair_flatvalue_168_169",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:170,find-plant:171,find-animal:170,find-animal:171 --methods flat provenance_value --duplication 1 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_expansion_170_171_retry_m1",
    "cp -a results_submission/scienceworld_local_qwen_expansion_170_171_retry_m1/requests results_submission/scienceworld_local_qwen_expansion_170_171_retry_m4",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:170,find-plant:171,find-animal:170,find-animal:171 --methods flat provenance_value --duplication 4 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_expansion_170_171_retry_m4",
    "python -m submission.local_qwen_expansion_summary --m1 results_submission/scienceworld_local_qwen_expansion_170_171_retry_m1 --m4 results_submission/scienceworld_local_qwen_expansion_170_171_retry_m4 --output results_submission/report/local_qwen_expansion_170_171_retry",
    "python -m submission.local_qwen_expanded_main_table",
    "python -m submission.local_qwen_expanded_main_table --expansion results_submission/report/local_qwen_expansion_162_164 results_submission/report/local_qwen_expansion_165_167 results_submission/report/local_qwen_expansion_170_171_retry --output results_submission/report/local_qwen_interactive_expanded_table_v3",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:172,find-plant:173,find-animal:172,find-animal:173 --methods flat provenance_value --duplication 1 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_expansion_172_173_m1",
    "cp -a results_submission/scienceworld_local_qwen_expansion_172_173_m1/requests results_submission/scienceworld_local_qwen_expansion_172_173_m4",
    "LOCAL_QWEN_DEVICE=cuda PYTHONPATH=/home/xhj/miniconda3/lib/python3.14/site-packages:/home/xhj/JevAttention/.venv-research/lib/python3.11/site-packages python -m submission.scienceworld_runner --backend local_qwen --tasks find-plant find-animal --variation-ids find-plant:172,find-plant:173,find-animal:172,find-animal:173 --methods flat provenance_value --duplication 4 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_expansion_172_173_m4",
    "python -m submission.local_qwen_expansion_summary --m1 results_submission/scienceworld_local_qwen_expansion_172_173_m1 --m4 results_submission/scienceworld_local_qwen_expansion_172_173_m4 --output results_submission/report/local_qwen_expansion_172_173",
    "python -m submission.local_qwen_expanded_main_table --expansion results_submission/report/local_qwen_expansion_162_164 results_submission/report/local_qwen_expansion_165_167 results_submission/report/local_qwen_expansion_170_171_retry results_submission/report/local_qwen_expansion_172_173 --output results_submission/report/local_qwen_interactive_expanded_table_v4",
    "python -m submission.qwen_effect_heterogeneity",
    "PYTHONPATH=external/ScienceWorld-src:local_deps python -m submission.scienceworld_runner --backend local_qwen --tasks find-plant --variation-ids find-plant:174,find-plant:175,find-plant:176 --methods flat_value provenance_value --duplication 1 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_heldout174_176_m1",
    "PYTHONPATH=external/ScienceWorld-src:local_deps python -m submission.scienceworld_runner --backend local_qwen --tasks find-plant --variation-ids find-plant:174,find-plant:175,find-plant:176 --methods flat_value provenance_value --duplication 4 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_heldout174_176_m4",
    "python -m submission.local_qwen_expansion_summary --m1 results_submission/scienceworld_local_qwen_heldout174_176_m1 --m4 results_submission/scienceworld_local_qwen_heldout174_176_m4 --output results_submission/report/local_qwen_heldout174_176",
    "PYTHONPATH=external/ScienceWorld-src:local_deps python -m submission.scienceworld_runner --backend local_qwen --tasks find-animal --variation-ids find-animal:177,find-animal:178,find-animal:179 --methods flat_value provenance_value --duplication 1 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_heldout177_179_m1",
    "PYTHONPATH=external/ScienceWorld-src:local_deps python -m submission.scienceworld_runner --backend local_qwen --tasks find-animal --variation-ids find-animal:177,find-animal:178,find-animal:179 --methods flat_value provenance_value --duplication 4 --steps 8 --workers 1 --output results_submission/scienceworld_local_qwen_heldout177_179_m4",
    "python -m submission.local_qwen_expansion_summary --m1 results_submission/scienceworld_local_qwen_heldout177_179_m1 --m4 results_submission/scienceworld_local_qwen_heldout177_179_m4 --output results_submission/report/local_qwen_heldout177_179",
    "python -m submission.qwen_bank_diagnostic",
    "python -m submission.qwen_semantic_bank_probe prepare",
    "LOCAL_QWEN_DEVICE=cuda python -m submission.qwen_semantic_bank_probe run",
    "python -m submission.qwen_semantic_bank_probe summarize",
    "python -m submission.paper_tables",
    "python submission/make_submission_pdf.py",
    "python -m pytest -q tests",
]


def digest(path: Path) -> dict:
    data = path.read_bytes()
    return {"path": str(path.relative_to(ROOT)), "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest()}


def run(output="results_submission/reproducibility_manifest.json", paper_output="paper/reproducibility.md"):
    existing = []
    missing = []
    for relative in FILES + SCRIPTS:
        path = ROOT / relative
        (existing if path.exists() else missing).append(path)
    packages = {}
    for name in ("numpy", "pandas", "scikit-learn", "matplotlib", "pytest", "requests"):
        try:
            packages[name] = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            packages[name] = None
    manifest = {
        "generated_by": "submission.reproducibility_manifest",
        "python": sys.version,
        "platform": platform.platform(),
        "packages": packages,
        "hashes": [digest(path) for path in existing],
        "missing": [str(path.relative_to(ROOT)) for path in missing],
        "commands": COMMANDS,
        "notes": [
            "Hashes cover frozen paper/report artifacts and generator scripts; raw API request caches remain archived beside their manifests.",
            "The manifest records evidence provenance and does not promote the broad interactive success claim.",
        ],
    }
    output_path = ROOT / output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
    lines = [
        "# Reproducibility manifest", "",
        "Generated by `python -m submission.reproducibility_manifest`.",
        "The manifest hashes the frozen paper/report artifacts and their generator scripts.", "",
        f"- Hashed files: {len(existing)}", f"- Missing files: {len(missing)}",
        f"- Python: {platform.python_version()}", "",
        "## Reproduction commands", "",
    ]
    lines.extend(f"{i}. `{command}`" for i, command in enumerate(COMMANDS, 1))
    lines += ["", "## Artifact hashes", "", "| Path | Bytes | SHA256 |", "|---|---:|---|"]
    lines.extend(f"| `{x['path']}` | {x['bytes']} | `{x['sha256']}` |" for x in manifest["hashes"])
    if missing:
        lines += ["", "## Missing at generation time", ""]
        lines.extend(f"- `{x}`" for x in manifest["missing"])
    (ROOT / paper_output).write_text("\n".join(lines) + "\n")
    print(json.dumps({"hashes": len(existing), "missing": len(missing), "output": output, "paper_output": paper_output}, indent=2))
    return manifest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="results_submission/reproducibility_manifest.json")
    parser.add_argument("--paper-output", default="paper/reproducibility.md")
    args = parser.parse_args()
    run(args.output, args.paper_output)


if __name__ == "__main__":
    main()
